// GENERATED by design/build_tokens.mjs — DO NOT EDIT.
// 값을 바꾸려면 design/design_tokens.json 를 고치고 `node design/build_tokens.mjs` 를 다시 실행한다.
// 디자인 시스템 교체도 이 파일이 아니라 design/design_tokens.json 에서 한다.
// 원본: SEED Design System (당근) (Apache License 2.0 (Copyright 2025 주식회사 당근마켓))

import 'package:flutter/widgets.dart';

/// 라이트/다크 각각 한 벌. 두 팔레트는 항상 같은 필드 집합을 갖는다(생성기가 강제).
@immutable
class DsPalette {
  final Color brandPrimary;
  final Color brandPrimaryHover;
  final Color brandPrimaryPressed;
  final Color brandPrimarySubtle;
  final Color brandPrimarySubtlePressed;
  final Color brandTextOnSubtle;
  final Color brandText;
  final Color brandOnPrimary;
  final Color neutralPrimaryBase;
  final Color neutralPrimaryOnBase;
  final Color surfaceBase;
  final Color surfaceRaised;
  final Color surfaceSunken;
  final Color surfaceOverlay;
  final Color surfacePressed;
  final Color textPrimary;
  final Color textSecondary;
  final Color textTertiary;
  final Color textDisabled;
  final Color textPlaceholder;
  final Color textInverted;
  final Color textOnBrand;
  final Color borderSubtle;
  final Color borderDefault;
  final Color borderStrong;
  final Color borderFocus;
  final Color statusSuccess;
  final Color statusWarning;
  final Color statusDanger;
  final Color statusInfo;
  final Color statusBgSuccess;
  final Color statusBgWarning;
  final Color statusBgDanger;
  final Color statusBgInfo;
  final Color inkPen;
  final Color inkPenBlue;
  final Color inkPenRed;
  final Color inkHighlighter;
  final Color inkHighlighterAlt;

  const DsPalette({
    required this.brandPrimary,
    required this.brandPrimaryHover,
    required this.brandPrimaryPressed,
    required this.brandPrimarySubtle,
    required this.brandPrimarySubtlePressed,
    required this.brandTextOnSubtle,
    required this.brandText,
    required this.brandOnPrimary,
    required this.neutralPrimaryBase,
    required this.neutralPrimaryOnBase,
    required this.surfaceBase,
    required this.surfaceRaised,
    required this.surfaceSunken,
    required this.surfaceOverlay,
    required this.surfacePressed,
    required this.textPrimary,
    required this.textSecondary,
    required this.textTertiary,
    required this.textDisabled,
    required this.textPlaceholder,
    required this.textInverted,
    required this.textOnBrand,
    required this.borderSubtle,
    required this.borderDefault,
    required this.borderStrong,
    required this.borderFocus,
    required this.statusSuccess,
    required this.statusWarning,
    required this.statusDanger,
    required this.statusInfo,
    required this.statusBgSuccess,
    required this.statusBgWarning,
    required this.statusBgDanger,
    required this.statusBgInfo,
    required this.inkPen,
    required this.inkPenBlue,
    required this.inkPenRed,
    required this.inkHighlighter,
    required this.inkHighlighterAlt,
  });

  static const light = DsPalette(
    brandPrimary: Color(0xFFFFB800),
    brandPrimaryHover: Color(0xFFE5A200),
    brandPrimaryPressed: Color(0xFFE5A200),
    brandPrimarySubtle: Color(0xFFFFF6DB),
    brandPrimarySubtlePressed: Color(0xFFFFEDB8),
    brandTextOnSubtle: Color(0xFF7A4F00),
    brandText: Color(0xFF8A5A00),
    brandOnPrimary: Color(0xFF1A1C20),
    neutralPrimaryBase: Color(0xFF1A1C20),
    neutralPrimaryOnBase: Color(0xFFFFFFFF),
    surfaceBase: Color(0xFFF3F4F5),
    surfaceRaised: Color(0xFFFFFFFF),
    surfaceSunken: Color(0xFFF7F8F9),
    surfaceOverlay: Color(0xFFFFFFFF),
    surfacePressed: Color(0xFFF7F8F9),
    textPrimary: Color(0xFF1A1C20),
    textSecondary: Color(0xFF555D6D),
    textTertiary: Color(0xFF6B7079),
    textDisabled: Color(0xFFD1D3D8),
    textPlaceholder: Color(0xFFB0B3BA),
    textInverted: Color(0xFFFFFFFF),
    textOnBrand: Color(0xFF1A1C20),
    borderSubtle: Color(0xFFDCDEE3),
    borderDefault: Color(0x10000000),
    borderStrong: Color(0xFF555D6D),
    borderFocus: Color(0xFF5E98FE),
    statusSuccess: Color(0xFF079171),
    statusWarning: Color(0xFFA85400),
    statusDanger: Color(0xFFFA342C),
    statusInfo: Color(0xFF217CF9),
    statusBgSuccess: Color(0xFFEDFAF6),
    statusBgWarning: Color(0xFFFFEDDD),
    statusBgDanger: Color(0xFFFDF0F0),
    statusBgInfo: Color(0xFFEFF6FF),
    inkPen: Color(0xFF1A1C20),
    inkPenBlue: Color(0xFF5E98FE),
    inkPenRed: Color(0xFFFC6A66),
    inkHighlighter: Color(0xFFE9C647),
    inkHighlighterAlt: Color(0xFFFBDC65),
  );

  static const dark = DsPalette(
    brandPrimary: Color(0xFFFFC53D),
    brandPrimaryHover: Color(0xFFFFD466),
    brandPrimaryPressed: Color(0xFFFFD466),
    brandPrimarySubtle: Color(0xFF332A12),
    brandPrimarySubtlePressed: Color(0xFF4A3A16),
    brandTextOnSubtle: Color(0xFFFFCC5C),
    brandText: Color(0xFFFFC53D),
    brandOnPrimary: Color(0xFF1A1C20),
    neutralPrimaryBase: Color(0xFF2B2E35),
    neutralPrimaryOnBase: Color(0xFFF3F4F5),
    surfaceBase: Color(0xFF000000),
    surfaceRaised: Color(0xFF16171B),
    surfaceSunken: Color(0xFF1D2025),
    surfaceOverlay: Color(0xFF1D2025),
    surfacePressed: Color(0xFF2B2E35),
    textPrimary: Color(0xFFF3F4F5),
    textSecondary: Color(0xFFDCDEE3),
    textTertiary: Color(0xFFB0B3BA),
    textDisabled: Color(0xFF5B606A),
    textPlaceholder: Color(0xFF868B94),
    textInverted: Color(0xFF16171B),
    textOnBrand: Color(0xFF1A1C20),
    borderSubtle: Color(0xFF393D46),
    borderDefault: Color(0x17FFFFFF),
    borderStrong: Color(0xFFDCDEE3),
    borderFocus: Color(0xFF1E82EB),
    statusSuccess: Color(0xFF22B27F),
    statusWarning: Color(0xFFFF9E4D),
    statusDanger: Color(0xFFFF6E60),
    statusInfo: Color(0xFF41A2F9),
    statusBgSuccess: Color(0xFF202926),
    statusBgWarning: Color(0xFF3A2A18),
    statusBgDanger: Color(0xFF322323),
    statusBgInfo: Color(0xFF202742),
    inkPen: Color(0xFFF3F4F5),
    inkPenBlue: Color(0xFF1E82EB),
    inkPenRed: Color(0xFFF73526),
    inkHighlighter: Color(0xFF714E15),
    inkHighlighterAlt: Color(0xFF543E15),
  );
}

class DsSpace {
  const DsSpace._();
  static const s0 = 0.0;
  static const s1 = 4.0;
  static const s2 = 8.0;
  static const s3 = 12.0;
  static const s4 = 16.0;
  static const s6 = 24.0;
  static const s8 = 32.0;
  static const s12 = 48.0;
  static const s16 = 64.0;
}

class DsRadius {
  const DsRadius._();
  static const base = 8.0;
  static const sm = 4.0;
  static const md = 6.0;
  static const lg = 8.0;
  static const xl = 12.0;
  static const r2xl = 16.0;
  static const r3xl = 20.0;
  static const r4xl = 24.0;
  static const full = 9999.0;
}

@immutable
class DsTypeStyle {
  final double size;
  final double lineHeight;
  final int weight;
  final double letterSpacing;
  const DsTypeStyle({
    required this.size,
    required this.lineHeight,
    required this.weight,
    required this.letterSpacing,
  });
}

class DsType {
  const DsType._();
  static const display = DsTypeStyle(size: 32.0, lineHeight: 1.31, weight: 700, letterSpacing: -0.20);
  static const h1 = DsTypeStyle(size: 26.0, lineHeight: 1.35, weight: 700, letterSpacing: -0.20);
  static const h2 = DsTypeStyle(size: 22.0, lineHeight: 1.36, weight: 700, letterSpacing: -0.20);
  static const h3 = DsTypeStyle(size: 18.0, lineHeight: 1.33, weight: 500, letterSpacing: 0.00);
  static const bodyLg = DsTypeStyle(size: 16.0, lineHeight: 1.38, weight: 400, letterSpacing: 0.00);
  static const body = DsTypeStyle(size: 14.0, lineHeight: 1.36, weight: 400, letterSpacing: 0.00);
  static const caption = DsTypeStyle(size: 13.0, lineHeight: 1.38, weight: 400, letterSpacing: 0.00);
  static const code = DsTypeStyle(size: 13.0, lineHeight: 1.38, weight: 400, letterSpacing: 0.00);
}

class DsShadow {
  const DsShadow._();
  static const sm = <BoxShadow>[BoxShadow(color: Color(0x14000000), offset: Offset(0.0, 1.0), blurRadius: 4.0)];
  static const md = <BoxShadow>[BoxShadow(color: Color(0x1A000000), offset: Offset(0.0, 2.0), blurRadius: 10.0)];
  static const lg = <BoxShadow>[BoxShadow(color: Color(0x1F000000), offset: Offset(0.0, 4.0), blurRadius: 16.0)];
}

/// 시간. 짧을수록 자주 쓰는 것이다 — 자주 보는 움직임이 길면 앱이 느려 보인다.
class DsMotion {
  const DsMotion._();
  static const instant = Duration(milliseconds: 90);
  static const fast = Duration(milliseconds: 160);
  static const base = Duration(milliseconds: 240);
  static const slow = Duration(milliseconds: 360);
  static const slower = Duration(milliseconds: 520);

  /// 목록 항목 사이의 시차. 이보다 크면 줄줄이 따라 들어오는 것이 눈에 보인다.
  static const stagger = Duration(milliseconds: 40);

  /// 등장할 때 올라오는 거리(dp). 크게 주면 '움직임'이 아니라 '이동'이 된다.
  static const travel = 12.0;

  /// 눌렀을 때 줄어드는 비율. 손끝이 닿았다는 것을 화면이 인정하는 최소한의 크기다.
  static const pressScale = 0.97;
}

/// 곡선. 전부 감속(easeOut) 계열이다 — 애플의 움직임이 그렇고, 감속은 '놓았다'로 읽힌다.
class DsCurve {
  const DsCurve._();
  static const standard = Cubic(0.32, 0.72, 0, 1);
  static const enter = Cubic(0.22, 1, 0.36, 1);
  static const exit = Cubic(0.4, 0, 1, 1);
  static const emphasized = Cubic(0.16, 1, 0.3, 1);
  static const spring = Cubic(0.34, 1.4, 0.64, 1);
}

class DsFont {
  const DsFont._();
  static const sans = <String>['Pretendard Variable', 'Pretendard', '-apple-system', 'BlinkMacSystemFont', 'Apple SD Gothic Neo', 'system-ui', 'sans-serif'];
  static const family = "Pretendard Variable";
}

/// 학습지 문서 계층. sheetWidth 는 필기 좌표계의 기준이라 변경 금지.
class DsWorksheet {
  const DsWorksheet._();
  static const sheetWidth = 820.0;
  static const pagePadding = 80.0;
  static const sectionGap = 72.0;
  static const blockGap = 28.0;
  static const ruleWidth = 1.0;
  static const inkSm = 96.0;
  static const inkMd = 160.0;
  static const inkLg = 240.0;
  static const body = DsTypeStyle(size: 18.0, lineHeight: 1.78, weight: 400, letterSpacing: 0.00);
  static const sectionTitle = DsTypeStyle(size: 26.0, lineHeight: 1.35, weight: 700, letterSpacing: 0.00);
  static const sectionNum = DsTypeStyle(size: 13.0, lineHeight: 1.00, weight: 700, letterSpacing: 0.00);
  static const quizQuestion = DsTypeStyle(size: 18.0, lineHeight: 1.70, weight: 500, letterSpacing: 0.00);
  static const caption = DsTypeStyle(size: 14.0, lineHeight: 1.60, weight: 400, letterSpacing: 0.00);
  static const lead = DsTypeStyle(size: 21.0, lineHeight: 1.72, weight: 500, letterSpacing: 0.00);
}
