// GENERATED by design/build_tokens.mjs — DO NOT EDIT.
// 값을 바꾸려면 design/design_tokens.json 를 고치고 `node design/build_tokens.mjs` 를 다시 실행한다.
// 디자인 시스템 교체도 이 파일이 아니라 design/design_tokens.json 에서 한다.
// 원본: Orca Design System (MIT (Copyright (c) 2026 Lovecast Inc.))

import 'package:flutter/widgets.dart';

/// 라이트/다크 각각 한 벌. 두 팔레트는 항상 같은 필드 집합을 갖는다(생성기가 강제).
@immutable
class DsPalette {
  final Color brandPrimary;
  final Color brandPrimaryHover;
  final Color brandPrimaryPressed;
  final Color brandPrimarySubtle;
  final Color brandOnPrimary;
  final Color neutralPrimaryBase;
  final Color neutralPrimaryOnBase;
  final Color surfaceBase;
  final Color surfaceRaised;
  final Color surfaceSunken;
  final Color surfaceOverlay;
  final Color textPrimary;
  final Color textSecondary;
  final Color textTertiary;
  final Color textDisabled;
  final Color textOnBrand;
  final Color borderSubtle;
  final Color borderDefault;
  final Color borderStrong;
  final Color borderFocus;
  final Color statusSuccess;
  final Color statusWarning;
  final Color statusDanger;
  final Color statusInfo;
  final Color inkPen;
  final Color inkPenBlue;
  final Color inkPenRed;
  final Color inkHighlighter;
  final Color inkHighlighterAlt;

  const DsPalette({
    required this.brandPrimary,
    required this.brandPrimaryHover,
    required this.brandPrimaryPressed,
    required this.brandPrimarySubtle,
    required this.brandOnPrimary,
    required this.neutralPrimaryBase,
    required this.neutralPrimaryOnBase,
    required this.surfaceBase,
    required this.surfaceRaised,
    required this.surfaceSunken,
    required this.surfaceOverlay,
    required this.textPrimary,
    required this.textSecondary,
    required this.textTertiary,
    required this.textDisabled,
    required this.textOnBrand,
    required this.borderSubtle,
    required this.borderDefault,
    required this.borderStrong,
    required this.borderFocus,
    required this.statusSuccess,
    required this.statusWarning,
    required this.statusDanger,
    required this.statusInfo,
    required this.inkPen,
    required this.inkPenBlue,
    required this.inkPenRed,
    required this.inkHighlighter,
    required this.inkHighlighterAlt,
  });

  static const light = DsPalette(
    brandPrimary: Color(0xFF7C5CFF),
    brandPrimaryHover: Color(0xFF6A46F5),
    brandPrimaryPressed: Color(0xFF5B37E0),
    brandPrimarySubtle: Color(0xFFF1EDFF),
    brandOnPrimary: Color(0xFFFAFAFA),
    neutralPrimaryBase: Color(0xFF171717),
    neutralPrimaryOnBase: Color(0xFFFAFAFA),
    surfaceBase: Color(0xFFFFFFFF),
    surfaceRaised: Color(0xFFFFFFFF),
    surfaceSunken: Color(0xFFF5F5F5),
    surfaceOverlay: Color(0xFFFFFFFF),
    textPrimary: Color(0xFF0A0A0A),
    textSecondary: Color(0xFF737373),
    textTertiary: Color(0xFFA1A1A1),
    textDisabled: Color(0xFFD4D4D4),
    textOnBrand: Color(0xFFFAFAFA),
    borderSubtle: Color(0xFFF0F0F0),
    borderDefault: Color(0xFFE5E5E5),
    borderStrong: Color(0xFF868690),
    borderFocus: Color(0xFFA1A1A1),
    statusSuccess: Color(0xFF15803D),
    statusWarning: Color(0xFFD4A300),
    statusDanger: Color(0xFFE40014),
    statusInfo: Color(0xFF2563EB),
    inkPen: Color(0xFF111111),
    inkPenBlue: Color(0xFF2563EB),
    inkPenRed: Color(0xFFE40014),
    inkHighlighter: Color(0xFFF59E0B),
    inkHighlighterAlt: Color(0xFFFACC15),
  );

  static const dark = DsPalette(
    brandPrimary: Color(0xFFA78BFA),
    brandPrimaryHover: Color(0xFFB9A3FB),
    brandPrimaryPressed: Color(0xFF8B6DF0),
    brandPrimarySubtle: Color(0xFF241E3D),
    brandOnPrimary: Color(0xFF171717),
    neutralPrimaryBase: Color(0xFFE5E5E5),
    neutralPrimaryOnBase: Color(0xFF171717),
    surfaceBase: Color(0xFF0A0A0A),
    surfaceRaised: Color(0xFF171717),
    surfaceSunken: Color(0xFF262626),
    surfaceOverlay: Color(0xFF171717),
    textPrimary: Color(0xFFFAFAFA),
    textSecondary: Color(0xFFA1A1A1),
    textTertiary: Color(0xFF737373),
    textDisabled: Color(0xFF525252),
    textOnBrand: Color(0xFF171717),
    borderSubtle: Color(0x0AFFFFFF),
    borderDefault: Color(0x12FFFFFF),
    borderStrong: Color(0xFF71717A),
    borderFocus: Color(0xFF737373),
    statusSuccess: Color(0xFF86EFAC),
    statusWarning: Color(0xFFD4A300),
    statusDanger: Color(0xFFFF6568),
    statusInfo: Color(0xFF60A5FA),
    inkPen: Color(0xFFFAFAFA),
    inkPenBlue: Color(0xFF60A5FA),
    inkPenRed: Color(0xFFFF6568),
    inkHighlighter: Color(0xFFF59E0B),
    inkHighlighterAlt: Color(0xFFFACC15),
  );
}

class DsSpace {
  const DsSpace._();
  static const s0 = 0.0;
  static const s1 = 4.0;
  static const s2 = 8.0;
  static const s3 = 12.0;
  static const s4 = 16.0;
  static const s6 = 24.0;
  static const s8 = 32.0;
  static const s12 = 48.0;
  static const s16 = 64.0;
}

class DsRadius {
  const DsRadius._();
  static const base = 10.0;
  static const sm = 6.0;
  static const md = 8.0;
  static const lg = 10.0;
  static const xl = 14.0;
  static const r2xl = 18.0;
  static const r3xl = 22.0;
  static const r4xl = 26.0;
  static const full = 9999.0;
}

@immutable
class DsTypeStyle {
  final double size;
  final double lineHeight;
  final int weight;
  final double letterSpacing;
  const DsTypeStyle({
    required this.size,
    required this.lineHeight,
    required this.weight,
    required this.letterSpacing,
  });
}

class DsType {
  const DsType._();
  static const display = DsTypeStyle(size: 34.0, lineHeight: 1.24, weight: 700, letterSpacing: -0.60);
  static const h1 = DsTypeStyle(size: 26.0, lineHeight: 1.30, weight: 700, letterSpacing: -0.40);
  static const h2 = DsTypeStyle(size: 21.0, lineHeight: 1.36, weight: 650, letterSpacing: -0.30);
  static const h3 = DsTypeStyle(size: 17.0, lineHeight: 1.44, weight: 600, letterSpacing: -0.20);
  static const bodyLg = DsTypeStyle(size: 17.0, lineHeight: 1.60, weight: 400, letterSpacing: -0.10);
  static const body = DsTypeStyle(size: 15.0, lineHeight: 1.62, weight: 400, letterSpacing: -0.10);
  static const caption = DsTypeStyle(size: 13.0, lineHeight: 1.50, weight: 400, letterSpacing: 0.00);
  static const code = DsTypeStyle(size: 13.0, lineHeight: 1.55, weight: 400, letterSpacing: 0.00);
}

class DsShadow {
  const DsShadow._();
  static const sm = <BoxShadow>[BoxShadow(color: Color(0x0A000000), offset: Offset(0.0, 1.0), blurRadius: 2.0)];
  static const md = <BoxShadow>[BoxShadow(color: Color(0x14000000), offset: Offset(0.0, 2.0), blurRadius: 8.0)];
  static const lg = <BoxShadow>[BoxShadow(color: Color(0x2E000000), offset: Offset(0.0, 10.0), blurRadius: 24.0)];
}

class DsMotion {
  const DsMotion._();
  static const durationFast = Duration(milliseconds: 120);
  static const durationBase = Duration(milliseconds: 200);
  static const durationSlow = Duration(milliseconds: 320);
  static const easingStandard = Cubic(0.2, 0, 0, 1);
  static const easingEmphasized = Cubic(0.05, 0.7, 0.1, 1);
}

class DsFont {
  const DsFont._();
  static const sans = <String>['Geist', 'Pretendard Variable', 'Pretendard', '-apple-system', 'BlinkMacSystemFont', 'Apple SD Gothic Neo', 'Segoe UI', 'sans-serif'];
  static const family = "Geist";
}

/// 학습지 문서 계층. sheetWidth 는 필기 좌표계의 기준이라 변경 금지.
class DsWorksheet {
  const DsWorksheet._();
  static const sheetWidth = 820.0;
  static const pagePadding = 56.0;
  static const sectionGap = 32.0;
  static const inkSm = 96.0;
  static const inkMd = 160.0;
  static const inkLg = 240.0;
  static const body = DsTypeStyle(size: 17.0, lineHeight: 1.78, weight: 400, letterSpacing: 0.00);
  static const sectionTitle = DsTypeStyle(size: 22.0, lineHeight: 1.40, weight: 700, letterSpacing: -0.30);
  static const sectionNum = DsTypeStyle(size: 13.0, lineHeight: 1.00, weight: 700, letterSpacing: 0.40);
  static const quizQuestion = DsTypeStyle(size: 18.0, lineHeight: 1.70, weight: 600, letterSpacing: 0.00);
  static const caption = DsTypeStyle(size: 14.0, lineHeight: 1.60, weight: 400, letterSpacing: 0.00);
}
