#!/usr/bin/env node
/**
 * 필기 런타임(ESM 두 파일)을 학습지 HTML 에 인라인할 수 있는 IIFE 문자열로 묶는다.
 *
 *   node server/build-runtime.mjs          생성
 *   node server/build-runtime.mjs --check  최신인지 검사 (CI용)
 *
 * 출력: server/supabase/functions/_shared/ink-runtime.g.ts
 *
 * 소스를 ESM 으로 유지하는 이유는 ink-core.js 를 Node 에서 그대로 import 해서
 * 테스트하기 위해서다. 번들 단계에서만 import/export 를 걷어낸다.
 * 두 파일 다 우리가 쓰므로 전용 변환으로 충분하다 (번들러 의존성 없음).
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const INK = resolve(ROOT, 'server/supabase/functions/_shared/ink')
const OUT = resolve(ROOT, 'server/supabase/functions/_shared/ink-runtime.g.ts')

/** `export ` 키워드와 상대경로 import 문만 걷어낸다. */
function toScript(src, file) {
  const out = src
    .replace(/^import\s+\*\s+as\s+\w+\s+from\s+'\.\/[^']+'\s*$/gm, '')
    .replace(/^export\s+(?=(const|let|var|function|class))/gm, '')

  const leftover = out.match(/^\s*(import|export)\s/m)
  if (leftover) {
    throw new Error(`${file}: 변환하지 못한 모듈 구문이 있습니다 — ${leftover[0].trim()}`)
  }
  return out
}

const core = toScript(readFileSync(resolve(INK, 'ink-core.js'), 'utf8'), 'ink-core.js')
// 글루는 core.foo 로 코어를 부른다. 한 스코프에 합치므로 그 네임스페이스를 만들어 준다.
const runtime = toScript(readFileSync(resolve(INK, 'ink-runtime.js'), 'utf8'), 'ink-runtime.js')

const CORE_EXPORTS = [...core.matchAll(/^(?:const|let|var|function|class)\s+(\w+)/gm)].map((m) => m[1])
const namespace = `const core = { ${CORE_EXPORTS.join(', ')} };`

const bundle = `(function () {
'use strict';
${core}
${namespace}
${runtime}
})();`

// 문법이 실제로 유효한지 확인한다. 깨진 번들이 학습지에 박히면 필기가 통째로 죽는다.
try {
  new Function(bundle)
} catch (e) {
  console.error('번들 문법 오류:', e.message)
  process.exit(1)
}

const body = `// GENERATED by server/build-runtime.mjs — DO NOT EDIT.
// 소스: server/supabase/functions/_shared/ink/{ink-core.js, ink-runtime.js}
// 고치려면 소스를 고치고 \`node server/build-runtime.mjs\` 를 다시 실행한다.
// 코어 로직 테스트는 app/tests/ink-core.test.mjs.

export const INK_RUNTIME_JS = ${JSON.stringify(bundle)}
`

if (process.argv.includes('--check')) {
  const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : null
  if (current !== body) {
    console.error('[drift] ink-runtime.g.ts 가 소스와 어긋납니다. `node server/build-runtime.mjs` 후 커밋하세요.')
    process.exit(1)
  }
  console.log(`필기 런타임 번들 최신 상태 확인됨 (${(bundle.length / 1024).toFixed(1)}KB, core export ${CORE_EXPORTS.length}개)`)
} else {
  writeFileSync(OUT, body)
  console.log(`생성: server/supabase/functions/_shared/ink-runtime.g.ts (${(bundle.length / 1024).toFixed(1)}KB, core export ${CORE_EXPORTS.length}개)`)
}
