#!/usr/bin/env node
/**
 * Untitled UI 아이콘에서 ONPAR 가 쓰는 것만 골라 뽑는다.
 *
 *   node design/build_icons.mjs          생성
 *   node design/build_icons.mjs --check  최신인지 검사 (CI용)
 *
 * 출처: untitledui-js (MIT, Copyright (c) 2025 Emmanuel C. Alozie)
 *       Untitled UI Icons 를 MIT 로 포팅한 패키지다.
 *
 * 1,172개를 전부 담지 않는다. 학습지 HTML 에 인라인으로 들어가므로 파일 크기가 곧 비용이고,
 * 실제로 쓰는 것만 있어야 어떤 아이콘이 어디에 쓰이는지 추적할 수 있다.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const SRC = resolve(ROOT, 'node_modules/untitledui-js/dist/react/index.mjs')
const OUT_DART = resolve(ROOT, 'packages/design_system/lib/src/tokens/icons.g.dart')
const OUT_TS = resolve(ROOT, 'server/supabase/functions/_shared/icons.g.ts')

/** ONPAR 이름 → Untitled UI 이름. 왼쪽이 우리가 코드에서 부르는 이름이다. */
const ICONS = {
  // 학습지 11개 섹션
  secWhatWeLearn: 'Target01',
  secBeforeAndNeed: 'ClockRewind',
  secPrerequisites: 'BookOpen01',
  secOriginStory: 'Hourglass01',
  secRoleplay: 'MessageChatCircle',
  secMainLesson: 'GraduationHat01',
  secProTips: 'Lightbulb02',
  secQuiz: 'HelpCircle',
  secHomework: 'CheckSquare',
  secWrapUp: 'Flag01',
  secNextSteps: 'Rocket01',
  // 학습지 문서 요소
  analogy: 'Stars01',
  glossary: 'BookOpen02',
  guide: 'MessageChatSquare',
  // 필기 툴바
  pen: 'PenTool02',
  highlighter: 'Brush01',
  eraser: 'Eraser',
  undo: 'FlipBackward',
  redo: 'FlipForward',
  clearAll: 'Trash01',
  zoomIn: 'ZoomIn',
  // 앱 내비게이션
  home: 'Home01',
  library: 'BookOpen01',
  review: 'RefreshCcw01',
  settings: 'Settings01',
  profile: 'User01',
  // 동작
  create: 'Plus',
  search: 'SearchLg',
  back: 'ChevronLeft',
  close: 'XClose',
  more: 'DotsVertical',
  // 상태
  success: 'CheckCircle',
  warning: 'AlertTriangle',
  danger: 'AlertCircle',
  info: 'InfoCircle',
}

const src = readFileSync(SRC, 'utf8')

/** `X = C("IconName", [["path", { d: "...", key: "..." }], ...])` 에서 name → path 목록을 뽑는다. */
function extract(name) {
  const re = new RegExp(`=\\s*[A-Za-z0-9_$]+\\("${name}",(\\[\\[[\\s\\S]*?\\]\\])\\)`, 'm')
  const m = re.exec(src)
  if (!m) throw new Error(`Untitled UI 에 없는 아이콘: ${name}`)
  const paths = [...m[1].matchAll(/d:\s*"([^"]+)"/g)].map((p) => p[1])
  if (paths.length === 0) throw new Error(`path 를 못 찾았습니다: ${name}`)
  return paths
}

const resolved = {}
for (const [ours, theirs] of Object.entries(ICONS)) {
  resolved[ours] = { source: theirs, paths: extract(theirs) }
}

const BANNER = `// GENERATED by design/build_icons.mjs — DO NOT EDIT.
// 아이콘을 추가하려면 design/build_icons.mjs 의 ICONS 에 넣고 다시 실행한다.
//
// 출처: Untitled UI Icons — untitledui-js (MIT, Copyright (c) 2025 Emmanuel C. Alozie)
// 선 굵기는 2px, 뷰박스는 24×24 로 통일되어 있다.`

const dart = `${BANNER}

/// SVG path 문자열. DsIcon 위젯이 flutter_svg 로 그린다.
class DsIcons {
  const DsIcons._();

  static const viewBox = 24.0;
  static const strokeWidth = 2.0;

${Object.entries(resolved).map(([k, v]) =>
  `  /// Untitled UI: ${v.source}\n  static const ${k} = <String>[\n${v.paths.map((p) => `    '${p}',`).join('\n')}\n  ];`
).join('\n\n')}

  static const all = <String, List<String>>{
${Object.keys(resolved).map((k) => `    '${k}': ${k},`).join('\n')}
  };
}
`

const ts = `${BANNER}

export const ICON_PATHS: Record<string, string[]> = ${JSON.stringify(
  Object.fromEntries(Object.entries(resolved).map(([k, v]) => [k, v.paths])), null, 2)}

export const ICON_SOURCE: Record<string, string> = ${JSON.stringify(
  Object.fromEntries(Object.entries(resolved).map(([k, v]) => [k, v.source])), null, 2)}

/**
 * 인라인 SVG 를 만든다. 학습지 HTML 은 외부 요청이 0이어야 하므로 아이콘도 문서에 직접 넣는다.
 * currentColor 를 쓰므로 색은 CSS 가 정한다.
 */
export function icon(name: string, size = 20, extraClass = ''): string {
  const paths = ICON_PATHS[name]
  if (!paths) throw new Error(\`등록되지 않은 아이콘: \${name}\`)
  return (
    \`<svg class="ico\${extraClass ? ' ' + extraClass : ''}" width="\${size}" height="\${size}" \` +
    'viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" ' +
    'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">' +
    paths.map((d) => \`<path d="\${d}"/>\`).join('') +
    '</svg>'
  )
}
`

const outputs = [[OUT_DART, dart], [OUT_TS, ts]]
const check = process.argv.includes('--check')
let drift = false
for (const [path, body] of outputs) {
  if (check) {
    if ((existsSync(path) ? readFileSync(path, 'utf8') : null) !== body) {
      console.error(`[drift] ${path.replace(ROOT + '/', '')} 가 어긋납니다.`)
      drift = true
    }
  } else {
    mkdirSync(dirname(path), { recursive: true })
    writeFileSync(path, body)
    console.log(`생성: ${path.replace(ROOT + '/', '')}`)
  }
}
if (check) {
  if (drift) { console.error('\n`node design/build_icons.mjs` 를 실행하고 커밋하세요.'); process.exit(1) }
  console.log(`아이콘 생성물 최신 상태 확인됨 (${Object.keys(resolved).length}개).`)
} else {
  const bytes = Object.values(resolved).reduce((n, v) => n + v.paths.join('').length, 0)
  console.log(`아이콘 ${Object.keys(resolved).length}개 · path 총 ${(bytes / 1024).toFixed(1)}KB`)
}
