#!/usr/bin/env node
/**
 * design_tokens.json 하나에서 Flutter 토큰과 학습지 CSS 토큰을 함께 생성한다.
 *
 *   node design/build_tokens.mjs          생성
 *   node design/build_tokens.mjs --check  생성물이 최신인지 검사 (CI용, 다르면 exit 1)
 *
 * 출력:
 *   packages/design_system/lib/src/tokens/tokens.g.dart
 *   server/supabase/functions/_shared/tokens.css.ts
 *
 * 의존성 없음. 이 파일과 design_tokens.json 만 있으면 돌아간다.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const SRC = resolve(ROOT, 'design/design_tokens.json')
const OUT_DART = resolve(ROOT, 'packages/design_system/lib/src/tokens/tokens.g.dart')
const OUT_CSS = resolve(ROOT, 'server/supabase/functions/_shared/tokens.css.ts')

const BANNER = (src) => `// GENERATED by design/build_tokens.mjs — DO NOT EDIT.
// 값을 바꾸려면 ${src} 를 고치고 \`node design/build_tokens.mjs\` 를 다시 실행한다.
// 디자인 시스템 교체도 이 파일이 아니라 ${src} 에서 한다.`

// ── 유틸 ────────────────────────────────────────────────────────────────
const isMeta = (k) => k.startsWith('_')
const strip = (v) =>
  Array.isArray(v) ? v.map(strip)
  : v && typeof v === 'object'
    ? Object.fromEntries(Object.entries(v).filter(([k]) => !isMeta(k)).map(([k, x]) => [k, strip(x)]))
    : v

const camel = (parts) =>
  parts.map((p, i) => (i === 0 ? p : p[0].toUpperCase() + p.slice(1))).join('')
const kebab = (parts) =>
  parts.join('-').replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()

/**
 * "#RGB" | "#RGBA" | "#RRGGBB" | "#RRGGBBAA" | "rgb(r g b / a)" | "rgba(r,g,b,a)" → {r,g,b,a}
 *
 * 8자리 hex 를 반드시 지원해야 한다. 알파를 담은 색을 이 형식으로 쓰는 디자인 시스템이 흔하고
 * (Seed 의 stroke.neutral-muted 가 #00000010 이다), 6자리만 받으면 그런 시스템으로 갈아끼울 때
 * 생성기가 통째로 멈춘다.
 */
function parseColor(input) {
  const s = String(input).trim()
  let m = /^#([0-9a-f]{3,4})$/i.exec(s)
  if (m) {
    const [r, g, b, a] = [...m[1]].map((c) => parseInt(c + c, 16))
    return { r, g, b, a: a === undefined ? 1 : a / 255 }
  }
  m = /^#([0-9a-f]{6})([0-9a-f]{2})?$/i.exec(s)
  if (m) {
    const n = parseInt(m[1], 16)
    return {
      r: (n >> 16) & 255, g: (n >> 8) & 255, b: n & 255,
      a: m[2] === undefined ? 1 : parseInt(m[2], 16) / 255,
    }
  }
  m = /^rgba?\(\s*([\d.]+)[\s,]+([\d.]+)[\s,]+([\d.]+)\s*(?:[/,]\s*([\d.]+)\s*)?\)$/i.exec(s)
  if (m) {
    return { r: +m[1], g: +m[2], b: +m[3], a: m[4] === undefined ? 1 : +m[4] }
  }
  throw new Error(`색상 파싱 실패: ${JSON.stringify(input)}`)
}

const hex2 = (n) => Math.round(n).toString(16).padStart(2, '0').toUpperCase()
const toDartColor = (v) => {
  const { r, g, b, a } = parseColor(v)
  return `Color(0x${hex2(a * 255)}${hex2(r)}${hex2(g)}${hex2(b)})`
}
const toCssColor = (v) => {
  const { r, g, b, a } = parseColor(v)
  return a === 1 ? `#${hex2(r)}${hex2(g)}${hex2(b)}` : `rgb(${r} ${g} ${b} / ${a})`
}

/** "0 1px 2px rgb(0 0 0 / 0.04)" → BoxShadow 인자 */
function parseShadow(s) {
  const m = /^(-?[\d.]+)(?:px)?\s+(-?[\d.]+)(?:px)?\s+(-?[\d.]+)(?:px)?\s+(.+)$/.exec(String(s).trim())
  if (!m) throw new Error(`그림자 파싱 실패: ${JSON.stringify(s)}`)
  return { dx: +m[1], dy: +m[2], blur: +m[3], color: m[4] }
}

// ── 색 토큰 평탄화 ───────────────────────────────────────────────────────
// color / colorDark 는 같은 키 집합을 가져야 한다. 다르면 테마 전환 시 구멍이 난다.
function flattenColors(obj, prefix = []) {
  const out = {}
  for (const [k, v] of Object.entries(obj)) {
    if (v && typeof v === 'object') Object.assign(out, flattenColors(v, [...prefix, k]))
    else out[[...prefix, k].join('.')] = v
  }
  return out
}

/**
 * 콜아웃 변수. accent·bg 가 {light, dark} 쌍이다.
 * 한쪽만 있으면 그 테마에서 대비가 무너지므로 없으면 생성기가 멈춘다.
 */
function calloutVars(t, theme) {
  return Object.entries(t.worksheet.callout).flatMap(([k, v]) => {
    for (const part of ['accent', 'bg']) {
      if (!v[part] || typeof v[part] !== 'object' || !v[part].light || !v[part].dark) {
        throw new Error(`worksheet.callout.${k}.${part} 에 light/dark 가 모두 있어야 합니다`)
      }
    }
    return [
      `  --ds-callout-${k}-accent: ${toCssColor(v.accent[theme])};`,
      `  --ds-callout-${k}-bg: ${toCssColor(v.bg[theme])};`,
    ]
  })
}

function assertPaletteParity(light, dark) {
  const l = Object.keys(light).sort()
  const d = Object.keys(dark).sort()
  const missing = l.filter((k) => !dark[k])
  const extra = d.filter((k) => !(k in light))
  if (missing.length || extra.length) {
    throw new Error(
      `라이트/다크 팔레트 키가 어긋납니다.\n  다크에 없음: ${missing.join(', ') || '-'}\n  라이트에 없음: ${extra.join(', ') || '-'}`
    )
  }
}

// ── Dart 생성 ───────────────────────────────────────────────────────────
function buildDart(t) {
  const light = flattenColors(t.color)
  const dark = flattenColors(t.colorDark)
  assertPaletteParity(light, dark)
  const keys = Object.keys(light)
  const field = (k) => camel(k.split('.'))

  const paletteFields = keys.map((k) => `  final Color ${field(k)};`).join('\n')
  const ctorArgs = keys.map((k) => `    required this.${field(k)},`).join('\n')
  const inst = (src) => keys.map((k) => `    ${field(k)}: ${toDartColor(src[k])},`).join('\n')

  const space = Object.entries(t.space).map(([k, v]) => `  static const s${k} = ${Number(v).toFixed(1)};`).join('\n')
  const radius = Object.entries(t.radius)
    .map(([k, v]) => `  static const ${/^\d/.test(k) ? 'r' + k : k} = ${Number(v).toFixed(1)};`).join('\n')

  const typeStyle = (name, s) =>
    `  static const ${name} = DsTypeStyle(size: ${Number(s.size).toFixed(1)}, ` +
    `lineHeight: ${Number(s.lineHeight).toFixed(2)}, weight: ${s.weight}, ` +
    `letterSpacing: ${Number(s.letterSpacing ?? 0).toFixed(2)});`
  const appType = Object.entries(t.typography.scale).map(([k, v]) => typeStyle(k, v)).join('\n')
  const wsType = Object.entries(t.worksheet.typography).map(([k, v]) => typeStyle(k, v)).join('\n')

  const shadow = Object.entries(t.shadow).map(([k, v]) => {
    const { dx, dy, blur, color } = parseShadow(v)
    return `  static const ${k} = <BoxShadow>[BoxShadow(color: ${toDartColor(color)}, offset: Offset(${dx.toFixed(1)}, ${dy.toFixed(1)}), blurRadius: ${blur.toFixed(1)})];`
  }).join('\n')

  const motion = Object.entries(t.motion)
    .filter(([k]) => k.startsWith('duration'))
    .map(([k, v]) => `  static const ${k} = Duration(milliseconds: ${v});`).join('\n')

  const ink = Object.entries(t.worksheet.inkSpace).map(([k, v]) => `  static const ink${k[0].toUpperCase()}${k.slice(1)} = ${Number(v).toFixed(1)};`).join('\n')
  const wsExtra = ['blockGap', 'ruleWidth'].map((k) => `  static const ${k} = ${Number(t.worksheet[k]).toFixed(1)};`).join('\n')

  return `${BANNER('design/design_tokens.json')}
// 원본: ${t.meta.base} (${t.meta.license})

import 'package:flutter/widgets.dart';

/// 라이트/다크 각각 한 벌. 두 팔레트는 항상 같은 필드 집합을 갖는다(생성기가 강제).
@immutable
class DsPalette {
${paletteFields}

  const DsPalette({
${ctorArgs}
  });

  static const light = DsPalette(
${inst(light)}
  );

  static const dark = DsPalette(
${inst(dark)}
  );
}

class DsSpace {
  const DsSpace._();
${space}
}

class DsRadius {
  const DsRadius._();
${radius}
}

@immutable
class DsTypeStyle {
  final double size;
  final double lineHeight;
  final int weight;
  final double letterSpacing;
  const DsTypeStyle({
    required this.size,
    required this.lineHeight,
    required this.weight,
    required this.letterSpacing,
  });
}

class DsType {
  const DsType._();
${appType}
}

class DsShadow {
  const DsShadow._();
${shadow}
}

class DsMotion {
  const DsMotion._();
${motion}
  static const easingStandard = Cubic(0.2, 0, 0, 1);
  static const easingEmphasized = Cubic(0.05, 0.7, 0.1, 1);
}

class DsFont {
  const DsFont._();
  static const sans = <String>[${t.typography.fontFamily.sans.split(',').map((f) => `'${f.trim().replace(/^'|'$/g, '')}'`).join(', ')}];
  static const family = ${JSON.stringify(t.typography.fontFamily.sans.split(',')[0].trim().replace(/^'|'$/g, ''))};
}

/// 학습지 문서 계층. sheetWidth 는 필기 좌표계의 기준이라 변경 금지.
class DsWorksheet {
  const DsWorksheet._();
  static const sheetWidth = ${Number(t.worksheet.sheetWidth).toFixed(1)};
  static const pagePadding = ${Number(t.worksheet.pagePadding).toFixed(1)};
  static const sectionGap = ${Number(t.worksheet.sectionGap).toFixed(1)};
${wsExtra}
${ink}
${wsType}
}
`
}

// ── CSS 생성 ────────────────────────────────────────────────────────────
function buildCss(t) {
  const light = flattenColors(t.color)
  const dark = flattenColors(t.colorDark)
  assertPaletteParity(light, dark)

  const decl = (name, val) => `  --ds-${name}: ${val};`
  const colorVars = (src) =>
    Object.entries(src).map(([k, v]) => decl(`color-${kebab(k.split('.'))}`, toCssColor(v))).join('\n')

  const scalars = [
    ...Object.entries(t.space).map(([k, v]) => decl(`space-${k}`, `${v}px`)),
    ...Object.entries(t.radius).map(([k, v]) => decl(`radius-${k}`, `${v}px`)),
    ...Object.entries(t.shadow).map(([k, v]) => decl(`shadow-${k}`, toCssColor ? String(v) : v)),
    decl('font-sans', t.typography.fontFamily.sans),
    decl('font-mono', t.typography.fontFamily.mono),
    decl('sheet-width', `${t.worksheet.sheetWidth}px`),
    decl('sheet-padding', `${t.worksheet.pagePadding}px`),
    decl('sheet-section-gap', `${t.worksheet.sectionGap}px`),
    ...Object.entries(t.worksheet.inkSpace).map(([k, v]) => decl(`ink-space-${k}`, `${v}px`)),
    ...Object.entries(t.worksheet.typography).flatMap(([k, v]) => [
      decl(`ws-${kebab([k])}-size`, `${v.size}px`),
      decl(`ws-${kebab([k])}-lh`, String(v.lineHeight)),
      decl(`ws-${kebab([k])}-weight`, String(v.weight)),
    ]),
    ...calloutVars(t, 'light'),
    decl('sheet-block-gap', `${t.worksheet.blockGap}px`),
    decl('paper', toCssColor(t.worksheet.paper.light)),
  ].join('\n')

  // 콜아웃도 테마를 탄다. 한 값만 두면 다크에서 밝은 배경 위에 밝은 글자가 얹혀 안 보인다.
  const calloutDark = calloutVars(t, 'dark').join('\n')

  const css = `:root {
${colorVars(light)}
${scalars}
}
:root[data-theme="dark"] {
${colorVars(dark)}
${calloutDark}
  --ds-paper: ${toCssColor(t.worksheet.paper.dark)};
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${colorVars(dark).split('\n').map((l) => '  ' + l).join('\n')}
${calloutDark.split('\n').map((l) => '  ' + l).join('\n')}
    --ds-paper: ${toCssColor(t.worksheet.paper.dark)};
  }
}`

  return `${BANNER('design/design_tokens.json')}
// 원본: ${t.meta.base} (${t.meta.license})
//
// 학습지 HTML 의 <style> 최상단에 그대로 삽입된다. 레이아웃 규칙은 worksheet.css.ts 가 갖는다.

export const TOKENS_CSS = ${JSON.stringify(css)}
`
}

// ── 실행 ────────────────────────────────────────────────────────────────
const tokens = strip(JSON.parse(readFileSync(SRC, 'utf8')))

const unresolved = JSON.stringify(tokens).match(/"TBD"/g)
if (unresolved) {
  console.error(`design_tokens.json 에 미해결 TBD 가 ${unresolved.length}개 남아 있습니다.`)
  process.exit(1)
}

const outputs = [
  [OUT_DART, buildDart(tokens)],
  [OUT_CSS, buildCss(tokens)],
]

const check = process.argv.includes('--check')
let drift = false
for (const [path, body] of outputs) {
  if (check) {
    const current = existsSync(path) ? readFileSync(path, 'utf8') : null
    if (current !== body) {
      console.error(`[drift] ${path.replace(ROOT + '/', '')} 가 design_tokens.json 과 어긋납니다.`)
      drift = true
    }
  } else {
    mkdirSync(dirname(path), { recursive: true })
    writeFileSync(path, body)
    console.log(`생성: ${path.replace(ROOT + '/', '')}`)
  }
}
if (check) {
  if (drift) {
    console.error('\n`node design/build_tokens.mjs` 를 실행하고 결과를 커밋하세요.')
    process.exit(1)
  }
  console.log('토큰 생성물 최신 상태 확인됨.')
}
